name: TitlesPlugin
main: me.semakon.TitlesPlugin
version: 2.1
commands:
  titles:
    description: Provides access to the Titles commands.
    usage: |
           Usage:
           /<command> - Opens the GUI for easy title selecting.
           /<command> set title <title> - Sets current title to <title>.
           /<command> set title - Disable current title.
           /<command> get titles [category] [<category>] - Print all available titles or all available titles from <category>.
           /<command> get titles user <user> - Print all titles unlocked by <user>.
           /<command> get title <title> description - Print description of <title>.
           /<command> get title <title> category - Print category of <title>.
           /<command> get request [user] [<user>] - Print pending request of self or <user>.
           /<command> get requests - Print all pending requests.
           /<command> get categories - Print all categories.
           /<command> create title <name> <description> [<category>] - Create a new title called <name> with <description> and <category>.
           /<command> create category <name> - Create a new category called <name>.
           /<command> remove title <title> - Completely remove <title> from TitlesPlugin.
           /<command> remove category <category> - Completely remove <category> from TitlesPlugin.
           /<command> edit <title> description <description> - Edit description of <title>.
           /<command> edit <title> category <category> - Change category of <title> to <category>.
           /<command> rename title <title> <newName> - Rename <title> to <newName>.
           /<command> rename category <category> <newName> - Rename <category> to <newName>.
           /<command> user <user> add title <title> - Add <title> to unlocked list of <user>.
           /<command> user <user> remove title <title> - Remove <title> from unlocked list of <user>.
           /<command> user <user> set title <title> - Sets current title of <user> to <title>.
           /<command> request tp user <user> - Teleports the sender to the location where the request of <user> was submitted.
           /<command> request approve user <user> - Approve title request of <user>.
           /<command> request deny <user> - Deny title request of <user>.
           /<command> request submit title <title> - Submit title request for <title>.
           /<command> request retract - Retract title request.
  autosave:
    description: Toggle autosave.
    usage: /<command>
